name: CI_CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Gauge
        run: |
          sudo apt-get install -y gauge

      - name: Install Java Plugin
        run: |
          gauge install java

      - name: Build and run tests
        run: mvn clean test

      - name: Run Gauge Tests
        run: gauge run specs/

      - name: Run CheckStyle
        run: mvn checkstyle:checkstyle

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.3.0:spotbugs

      - name: Save XML Report
        uses: actions/upload-artifact@v4
        with:
          name: gauge-xml-report
          path: reports/xml-report/

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
