name: CI_CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Run Javalin server in background
        run: java -jar target/*.jar &

      - name: Wait for server to be ready
        run: |
            for i in {1..10}; do
              if curl -s http://localhost:7000/health; then
                echo "Server is up"
                break
              fi
                echo "Waiting for server..."
                sleep 3
            done

      - name: Run Postman tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/Fluffy.postman_collection.json
          environment: postman/myEnvironment.postman_environment.json

      - name: Build and run tests
        run: | 
          mvn clean test

      - name: Run CheckStyle
        run: mvn checkstyle:checkstyle

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.3.0:spotbugs

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
